#!/bin/sh

cp -r ../.pio/libdeps/esp32-c3/Crypto .

# exit 0

for n in ../src/crypto.* ../src/utils.* ../src/constants.h ../src/importexport.{h,cpp} ; do
    fname=$(basename $n)
    cp $n $fname
done
