#!/bin/sh
./generate plop | grep -v '^#' | ./decoderaw plop
echo " ~ single ~"
./encoderaw abc 0 2 MAXIMUM_LABEL_LENGTH_END_IN__X MAXIMUM_PASSWORD_SIZE_END_IN___X | ./decoderaw abc
echo "Previous should be same as:"
export KPASS=1
./encoderaw abc 0 2 MAXIMUM_LABEL_LENGTH_END_IN__X MAXIMUM_PASSWORD_SIZE_END_IN___X | ./decoderaw abc
echo "Should show garbage:"
./encoderaw abc 1 2 MAXIMUM_LABEL_LENGTH_END_IN__X MAXIMUM_PASSWORD_SIZE_END_IN___X | ./decoderaw abc
echo "Python version:"
./keypass.py -c plop dump -l toto -p pass --index 0 | ./keypass.py -c plop parse
