name: PlatformIO CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hw_type: [0, 1, 2]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install platformio

      - name: Build HW_TYPE=${{ matrix.hw_type }}
        run: pio run -e esp32-c3v${{ matrix.hw_type }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KeyPass-ESP32-C3-HW${{ matrix.hw_type }}
          path: .pio/build/esp32-c3v${{ matrix.hw_type }}/*.bin
